# -*- coding: utf-8 -*-
"""END_Session8_Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YiHjS3axRP5QzBAe16vqFz5l19Ge6bpj
"""

# Write a python function which takes variable no of arguments and print them

def print_arguments(*args):
    for i in args:
        print(i)

# Write a python function that takes a list and returns a list with unique elements
def unique(ll):
  return list(set(ll))

print(unique([1,2,3,3,10,3,3,4,5]))

# Write a python function which takes variable no of arguments and returns a list containing the arguments
def append_into_list(*args):
    l = []
    for i in args:
        l.append(i)
    return l

# write a python function to find whether all elements in a list are different.

def if_unique(ll):
  return len(ll) == len(set(ll))

# Write a python program to filter the numbers in a list which are divisible by a given number

l1 = [11, 45, 33, 73, 89, 131, 239, 721, 21]
n = 3
result = list(filter(lambda x: (x % n == 0), l1))
print(f"Numbers divisible by {n} are {result}")

# write a python function to find whether all elements in a list are same.

def if_same(ll):
  return len(set(ll)) == 1

# write a python function to check whether the input argument is palindrome

def is_palindrome(s):
    return s == s[::-1]

# write a function to check if a lower case letter exists in the input argument
def if_lower(s):
    for c in s: 
        k = c.islower()   
        if k == True: 
            return True 
    if(k != 1): 
        return False

# Write a program to swap first and last elements in a list
l1 = [1, 2, 3, 4, 5, 6]
print(l1)
l1[0], l1[-1] = l1[-1], l1[0]
print(l1)

# write a function to check if a upper case letter exists in the input argument

def check_upper(s):
    
    for c in s: 
        k = c.isupper()   
        if k == True: 
            return True
    if(k != 1): 
        return False

# Write a python function to return sum all the numbers in a list
def sum(numbers):
    total = 0
    for x in numbers:
        total += x
    return total

# Write a python function to multiply all the numbers in a list
def multiply(numbers):  
    total = 1
    for x in numbers:
        total *= x  
    return total

# Write a python function to calculate the factorial of a number through recursion
def fact(n):
    if n == 0:
        return 1
    else:
        return n * fact(n-1)

# Write a python function to print the number of upper case letters and lower case letters
def string_test(s):
    d={"u_c":0, "l_c":0}
    for c in s:
        if c.isupper():
           d["u_c"]+=1
        elif c.islower():
           d["l_c"]+=1
        else:
           pass
    print ("No. of Upper case letters : ", d["u_c"])
    print ("No. of Lower case letters : ", d["l_c"])

# Write a python function to return the even numbers from list

def is_even_num(l):
    ll = []
    for n in l:
        if n % 2 == 0:
            ll.append(n)
    return ll

# Write a python function to return the odd numbers from list

def is_odd_num(l):
    ll = []
    for n in l:
        if n % 2 != 0:
            ll.append(n)
    return ll

# Write a python function to remove element at an index from a list 

def remove_ele(sample_list, pos):
  sample_list.pop(pos)
  return sample_list

# Write a python function to insert element at an index in a list 
def insert_ele(sample_list, pos, ele):
  sample_list.insert(pos, ele)
  return sample_list

# Write a python function to return sum of squares of first n natural numbers
def sum_of_squares(n):
  s = 0
  for i in range(1, n+1):
    s += i**2
  return s

# Write a python function to return the area of sqaure given side length

def area_sq(a):
    return a*a

# Write a python function to return the perimeter of sqaure given side length

def perimeter_sq(a):
    return a * 4

# Write a python function to return the perimeter of rectangle given length and breadth

def perimeter_rec(l,b):
    return 2*(l + b)

# Write a python function to return the area of rectangle given length and breadth

def area_rec(l,b):
    return l*b

# Write a python function to return index of a given elemement in list

def return_index_in_list(sample_list, ele):
  return sample_list.index(ele)

# Write a python function to return the list reversed
def list_reversed(ll):
  ll.reverse()
  return ll

# Write a python function to swap two tuples
def swap_tuples(t1,t2):
  t1,t2 = t2,t1
  return t1,t2

# Write a python function to sort a list of tuples by 2nd item

def sort_tuple_list(ll):
  return sorted(ll, key=lambda x: x[1])

# Write a python program to print multiplication table of a number

n = 2
for i in range(1, 11, 1):
    mult = n*i
    print(n, 'X', i , '=', mult)

# Write a python program to print fibonacci series upto n terms

n = 10
num1, num2 = 0, 1
count = 0

print("Fibonacci sequence:")
while count < n:
    print(num1, end="  ")
    temp = num1 + num2
    # update values
    num1 = num2
    num2 = temp
    count += 1

# Write a python program to find factorial of a number through loop
num = 7
fct = 1
if num < 0:
    print("Factorial does not exist for negative numbers")
elif num == 0:
    print("The factorial of 0 is 1")
else:
    for i in range(1, num + 1):
        fct = fct * i
    print("The factorial of", num, "is", fct)

# Write a python program to print an integer in reverse order

num = 76542
reverse_number = 0
print("Given Number ", num)
while num > 0:
    reminder = num % 10
    reverse_number = (reverse_number * 10) + reminder
    num = num // 10
print("Revered Number ", reverse_number)

# Write a python program to print area of a triangle given 3 sides length

a = 10
b = 20
c = 20

s = (a + b + c) / 2
area = (s*(s-a)*(s-b)*(s-c)) ** 0.5
print('Area is ', area)

# Write a python program to print area of a triangle given height and width

h = 10
w = 20
area = 1/2*(h*w)*1.0
print('Area is ', area)

# Write a python program to print cube of number upto a given integer

n = 10
for i in range(1, n + 1):
    print("Current Number is :", i, " and the cube is", (i * i * i))

# Write a python program to add an element to a dictionary

d = {0:10, 1:20}
print(d)
d.update({2:30})
print(d)

# Write a python function to return power of a number raised to another number

def power(a,b):
  if b == 1:
    return a
  else:
    return a*power(a, b-1)

# Write a python function to get length and breadth of a rectangle and check if it is a square

def check_if_square(length,breadth):
  if length == breadth:
    return True
  else:
    return False

# Write a python function to convert minutes into seconds

def minutes_to_seconds(mins):
  secs = mins * 60
  return secs

# Write a python function to convert kilometers into miles

def kms_to_miles(kms):
  miles = kms * 0.621371
  return miles

# Write a python function to convert hours into minutes

def hours_to_minutes(hrs):
  mins = hrs * 60
  return mins

# Write a python function to convert hours into seconds

def hours_to_seconds(hrs):
  secs = hrs * 60 * 60
  return secs

# Write a python function to convert celcius into Fahrenheit

def celcius_to_fahrenheit(c):
  f = ((c * 1.8) + 32)
  return f

# Write a python function to return area of a triangle given 3 sides length

def area_triangle(a,b,c):
  s = (a + b + c) / 2
  area = (s*(s-a)*(s-b)*(s-c)) ** 0.5
  return area

# Write a python function to return the last element in a list

def last_element(ll):
  lastEle = ll[len(ll) - 1]
  return lastEle

# write a python function to print type of each parameter passed

def parameter_types(*args):
    for i in args:
        print(type(i))

# write a python function to return number of vowels in input
def vowelCount(txt):
   c = 0
   for t in txt:
      if t in "aeiouAEIOU":
         c += 1
   return c

# write a python program to print a given string n number of times

txt = 'Hello there ! '
n = 10

print(txt*n)

# Write a python program to convert string into camel case

txt = 'hello, are you there?'
camel_case = txt.title()

print(camel_case)

# write a python function that interchanges the keys and values in a dictionary and returns it
def invert_dict(d):
   inverted_dict = {v: k for k, v in d.items()}
   return inverted_dict

# Write a program to to check if a triangle is valid or not, given length of 3 sides

def if_triangle_valid(s1, s2, s3):
    if s1>0 and s2>0 and s3>0:
        if s1+s2 > s3 and s1+s3 > s2 and s2+s3 > s1:
            return True
    return False

# Write a python function to sort a list of strings by length

def sort_tuple_list(ll):
  return sorted(ll, key=lambda x: len(x))

# Write a function to return the average of input arguments

def arg_avg(*args):
  return sum(args)/len(args)

# write a python function to return a sentence without punctuation
def withput_punctuations(txt):
   punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
   s = ''
   for char in txt:
      if char not in punctuations:
         s = s + char
   return s

# write a python function to print the binary representation of a  number
def binary_representation(n):
   print(bin(n))

# write a python function to print the octal representation of a  number
def octal_representation(n):
   print(oct(n))

# write a python function to print the hexadecimal representation of a  number
def hex_representation(n):
   print(hex(n))

# write a python program to print the count of letters and digits in sentence

sentence = 'Hello 1234 are you there 345'
d = 0
l = 0
for s in sentence:
   if s.isdigit():
      d += 1
   elif s.isalpha():
      l += 1
   else:
      pass
print(f'Digits: {d}, Letters: {l}')

# Write a function to calculate simple interest, given p, r, t
def simple_interest(p, r, t):
    interest = (p*r*t)/100
    return interest

# Write a function to calculate compound interest, given p, r, t
def compound_interest(p, r, t):
    amount = p * (1 + (r/100))**t
    interest = amount - p
    return interest

# write a python program to remove odd numbers from a list using list comprehensions

nums = [1, 2, 3, 4, 5, 6, 7, 8]
no_odd_nums = [i for i in nums if i % 2 == 0]

print(no_odd_nums)

# write a python program to remove even numbers from a list using list comprehensions

nums = [1, 2, 3, 4, 5, 6, 7, 8]
no_even_nums = [i for i in nums if i % 2 == 1]

print(no_even_nums)

# Write a python program to randomly select n elements from a list

import random
l1 = [2, 2, 4, 10, 3, 1, 6, 6, 8] 
n = 2
l2 = random.sample(l1, n)

print(l2)

# Write a python function to randomly return n elements from input list

def random_subset(l, n):
  import random
  return random.sample(l,n)

# Write a python function to print whether a number is negative or positive
def if_positive(n):
    if n >= 0:
       print("Positive")
    else:
       print("Negative")

# Write a python function to return area of a circle given radius

def area_circle(r): 
    return 3.142 * (r*r)

# Write a python function to return perimeter of a circle given radius

def perimeter_circle(r): 
    return 2 * 3.142 * r

# Write a function to return the nth day of week
def day_name(n):
  if n <= 7:
    dct = {1: 'Sunday', 2: 'Monday', 3: 'Tuesday', 4: 'Wednesday', 5: 'Thursday', 6: 'Friday', 7: 'Saturday'}
    return dct[n]
  else:
    print('A week has only 7 days')

# write a python function that sorts the input list through bubble sort algorithm

def bubble_sort(A):
  for i in range(len(A)):
    for k in range(len(A)-1, i, -1):
      if A[k] < A[k-1]:
        A[k],A[k-1] = A[k-1],A[k]

# write a python function that sorts the input list through insersion sort algorithm

def insertion_sort(A):
    for i in range(1,len(A)):
        temp = A[i]
        k = i
        while k >0 and temp < A[k-1]:
            A[k] = A[k-1]
            k -= 1
        A[k] = temp

# write a python function that returns the input list sorted in ascending order

def sort_list_asc(l):
    return sorted(l)

# write a python function that returns the input list sorted in descending order

def sort_list_desc(l):
    return sorted(l, reverse=True)

# Write a python function for z - normalization given mean and standard deviation

def z_normalize(l, m, sd):
  return [((x-m)/sd*1.0) for x in l]

# write a python function to convert elements of a list to percentage of total

def convert_perc(l):
  return[round((i*100.0/sum(l)),2) for i in l]

# write a python function to find what percentage of maximum value is each element

def perc_of_max(l):
  return[round((i*100.0/max(l)),2) for i in l]

# Write a python function to return pairwise combinations from a list

def create_pairs(l):
  return [(l[i],l[i+1]) for i in range(len(l)-1)]

# Write a python program to combine 2 lists as keys and values of a dictionary
l1 = [1,2,3]
l2 = ['a','b','c']

dic = dict(zip(l1,l2))
print(dic)

# write a python program to combine 2 lists as a list of tuples

l1 = [1,2,3]
l2 = ['a','b','c']

tp = list(zip(l1,l2))
print(dic)

# write a python program to print weighted average given list of numbers and weights

nos = [1,2,3,4]
wts = [1,0.4,0.2,0.4]

mult = [x*y for x,y in zip(nos, wts)]
sm = sum(mult)
weighted_average = sm/sum(wts)
print(weighted_average)

# write a python program to count the number of each vowel is a sentence

txt = 'Hello, are you there or not and if not then why not?'
txt = txt.lower()
dic = {x:sum([1 for c in txt if c == x]) for x in 'aeiou'}

print(dic)

# write a python program to find the square root of a number

n = 8
sq_rt = n**0.5

print(sq_rt)

# write a python program that prints out natural numbers given an input in reverse order
input_num = 32
while input_num:
    print(input_num)
    input_num -= 1

# write a python function to return if a number is an armstrong number

def is_armstrong(n):
  sum = 0
  temp = n
  while temp > 0:
   digit = temp % 10
   sum += digit ** 3
   temp //= 10
   if n == sum:
     return True
  else:
    return False

# write a python function to return factors of a given number

def factors(n):
  l = []
  for i in range(1, n + 1):
    if n % i == 0:
      l.append(i)
  return l

# write a python function that takes a list as an input and converts all numbers to positive numbers and returns the new list

def make_all_positive(nums):
   return [num if num > 0 else -num for num in nums]

# write a python function that takes a list as an input and converts all numbers to negative numbers and returns the new list

def make_all_negative(nums):
   return [num if num < 0 else -num for num in nums]

# write a program to return sum of n natural numbers dtarting from 1 given n

def sum_natural_nos(n):
  return n*(n+1)/2

# write a python function to add 2 lists element wise
def add_two_lists(list1, list2):
   sum_list = []
   for (item1, item2) in zip(list1, list2):
      sum_list.append(item1+item2)
   return sum_list

# write python function to find ASCII value of a character

def ascii_val(c):
  ascii_v = ord(c)
  return ascii_v

# write python function to find next character of input character

def next_char(c):
  ascii_v = ord(c)
  next_ascii = ascii_v + 1
  next_c = chr(next_ascii)
  return next_c

# write python function to find character from ascii value

def find_char(n):
  chr_v = chr(n)
  return chr_v

# write a python program to shuffle a deck

import itertools, random
deck = list(itertools.product(range(1,14),['Spade','Heart','Diamond','Club']))
random.shuffle(deck)

print(deck)

# write a python function to return mean of a list
def list_mean(l):
  s = sum(l)
  ln = len(l)
  return s/ln

# write a python function to return mean of a list
def list_median(l):
  ln = len(l)
  idx = ln // 2
  if ln % 2:
    return sorted(l)[idx]
  return sum(sorted(l)[idx - 1:idx + 1]) / 2

# write a python function to return common elements from 2 lists

def common_from_lists(l1,l2):
  comm_ele = list(set(l1).intersection(set(l2)))
  return comm_ele

# write a python program to convert a list to a dictionary where the key is the index and the value is the item in the list
my_list = [1, 8, 1, 2, 2, 9]
my_dict = {key: value for key, value in enumerate(my_list)}

# write a python function to reverse the sign of elements of a list

def reverse_sign(l):
  l2 = [-x for x in l]
  return l2

# Write a python function that seperate positive and negative numbers into seperate lists
def pos_neg(l):
    pl = []
    nl = []
    for n in l:
        if n<0:
            nl.append(n)
        else:
            pl.append(n)
    return pl,nl

# write a python function to check if a string is substring of another

def is_subString(s1,s2):
  if (s1.find(s2) == -1): 
      return False
  else: 
      return True

# write a python function that return number of spaces in given text
 
def count_spaces(txt): 
    count = 0
    for i in range(0, len(txt)): 
        if txt[i] == " ": 
            count += 1
    return count

# Write a function that returns the sum of digits of a given number
def digit_sum(n):
    sm=0
    while n > 0:
        d = n % 10
        sm+=d
        n//=10
    return sm